#include <stdio.h>
#include <stdlib.h>
#include <windows.h>
/* run this program using the console pauser or add your own getch, system("pause") or input loop */
void TextColor(int x) {
	HANDLE colour;
	colour = GetStdHandle(STD_OUTPUT_HANDLE);
	SetConsoleTextAttribute(colour, x);
}

void bestSellerInWeek() {
	TextColor(11);
	printf("\t _____________________________________________________________________\n\t|");
	TextColor(12);
	printf("                        Nhat Thi's Laptop Store                      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(14);
	printf("  List of Best-sellers in last week (from 05/02/2018 to 11/02/2018): ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(5);
	printf("       =====================================================         ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(9);
	printf("	     Product");
	TextColor(5);
	printf("	  |");
	TextColor(9);
	printf("    Type");
	TextColor(5);
	printf("   |");
	TextColor(9);
	printf(" Quantity");
	TextColor(5);
	printf(" |"); 
	TextColor(9); 
	printf("  Sold date	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  1. Inspiron");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 4 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 3");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   03/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("			     RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   05/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  2. Inspiron Duo");
	TextColor(5);
	printf(" |");
	TextColor(7);
	printf("  RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 3");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   07/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  3. Alienware");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf(" RAM 16 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   09/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  4. Vostro");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 4 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   10/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  5. Latitude");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   11/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(5);
	printf("       =====================================================         ");
	TextColor(11);
	printf("|\n\t|_____________________________________________________________________|\n");
}

void bestSellerInMonth() {
	TextColor(11);
	printf("\t _____________________________________________________________________\n\t|");
	TextColor(12);
	printf("                        Nhat Thi's Laptop Store                      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(14);
	printf(" List of Best-sellers in month [February] (from 01/02 to 28/02/2018) ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(5);
	printf("       =====================================================         ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(9);
	printf("	     Product");
	TextColor(5);
	printf("	  |");
	TextColor(9);
	printf("    Type");
	TextColor(5);
	printf("   |");
	TextColor(9);
	printf(" Quantity");
	TextColor(5);
	printf(" |"); 
	TextColor(9); 
	printf("  Sold date	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  1. Inspiron");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 4 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 3");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   03/02/2018       ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("			     RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   05/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  2. Inspiron Duo");
	TextColor(5);
	printf(" |");
	TextColor(7);
	printf("  RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 3");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   07/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  3. Alienware");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf(" RAM 16 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   09/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  4. Vostro");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 4 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   10/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(7);
	printf("	  5. Latitude");
	TextColor(5);
	printf("	  |");
	TextColor(7);
	printf("  RAM 8 GB");
	TextColor(5);
	printf(" |    ");
	TextColor(7);
	printf(" 2");
	TextColor(5);
	printf("    |");
	TextColor(7);
	printf("   11/02/2018	      ");
	TextColor(11);
	printf("|\n\t|                                                                     |\n\t|");
	TextColor(5);
	printf("       =====================================================         ");
	TextColor(11);
	printf("|\n\t|_____________________________________________________________________|\n");
}

void salesInMonth() {
	int num1, num2, num3, num4, num5, sum = 0;
	TextColor(11);
	printf("\t   *_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*\n\n");
	TextColor(12);
	printf("\t\t\t\tNhat Thi's Laptop Store\n\n");
	TextColor(14);
	printf("\t\t  Sales in [February] (from 01/02/2018 to 28/02/2018)\n\n");
	TextColor(5);
	printf("\t\t =====================================================\n\n");
	TextColor(9);
	printf("\t\t   Product");
	TextColor(5);
	printf("      |");
	TextColor(9);
	printf("  Type");
	TextColor(5);
	printf("     | ");
	TextColor(9); 
	printf(" Sold date");
	TextColor(5);
	printf("  |  ");
	TextColor(9);
	printf(" Price\n\n");
	TextColor(7);
	printf("\t\t1. Inspiron");
	TextColor(5);
	printf("     | ");
	TextColor(7);
	printf("RAM 4 GB");
	TextColor(5);
	printf("  |  ");
	TextColor(7);
	printf("03/02/2018");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	scanf("%d", &num1);
	TextColor(7);
	printf("\t\t2. Inspiron Duo");
	TextColor(5);
	printf(" | ");
	TextColor(7);
	printf("RAM 8 GB");
	TextColor(5);
	printf("  |  ");
	TextColor(7);
	printf("07/02/2018");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	scanf("%d", &num2);
	TextColor(7);
	printf("\t\t3. Alienware");
	TextColor(5);
	printf("    | ");
	TextColor(7);
	printf("RAM 16 GB");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	printf("09/02/2018");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	scanf("%d", &num3);
	TextColor(7);
	printf("\t\t4. Vostro");
	TextColor(5);
	printf("       | ");
	TextColor(7);
	printf("RAM 4 GB");
	TextColor(5);
	printf("  |  ");
	TextColor(7);
	printf("10/02/2018");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	scanf("%d", &num4);
	TextColor(7);
	printf("\t\t5. Latitude");
	TextColor(5);
	printf("     | ");
	TextColor(7);
	printf("RAM 8 GB");
	TextColor(5);
	printf("  |  ");
	TextColor(7);
	printf("11/02/2018");
	TextColor(5);
	printf(" |  ");
	TextColor(7);
	scanf("%d", &num5);
	sum = num1 + num2 + num3 + num4 + num5;
	TextColor(12);
	printf("\n\t\t\t\t Total = %d\n", sum);
	TextColor(11);
	printf("\t   *_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*_*");
}
